#! /usr/bin/php
<?php
/**
 * Inclui o arquivo necessário para iniciar qualquer script de linha de comando
 * que rode dentro do Spaghetti*.
 */
require_once "libs/bootstrap.php";

/**
 * Define a pasta raiz da biblioteca externa de shell.
 */
define("CONSOLE_ROOT", ROOT . "/script/libs/console/");

/**
 * Inclui o arquivo que inicia o console.
 */
require_once "libs/console/console.php";
?>