#! /usr/bin/php

<?php
/**
 *  Put description here.
 *
 *  Licensed under The MIT License.
 *  Redistributions of files must retain the above copyright notice.
 *  
 *  @package Spaghetti
 *  @subpackage Spaghetti.Script.Generate
 *  @license http://www.opensource.org/licenses/mit-license.php The MIT License
 * 
 */

$path = dirname(dirname(__FILE__));
require_once $path . DIRECTORY_SEPARATOR . "spaghetti.php";

App::import("Core", array("shell", "command", "task", "file", "folder"));

new ShellDispatcher();

?>