#! /usr/bin/php

<?php
/**
 *  Short Description
 *
 *  @license   http://www.opensource.org/licenses/mit-license.php The MIT License
 *  @copyright Copyright 2008-2009, Spaghetti* Framework (http://spaghettiphp.org/)
 *
 */

$path = dirname(dirname(__FILE__));
require_once $path . DIRECTORY_SEPARATOR . "spaghetti.php";

App::import("Core", array("shell", "command", "task", "file", "folder"));

new ShellDispatcher();

?>